domain: 'trieti.github.io'
url: 'https://trieti.github.io'
baseurl: '/'
permalink: pretty
title: 'Trieti Enterprises'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo-mobile.svg"
  desktop_height: "32px"
  desktop_width: "128px"
  text: "images/logo/logo-text.svg"

home: 
  limit_products: 6

collections:
  products:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
